---
- name: Configure Apache HTTP Server
  hosts: webservers # Or 'localhost' if running on the control node
  become: true      # Use sudo for privileged operations

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Apache HTTP Server
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Ensure Apache service is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy custom index.html
      ansible.builtin.copy:
        content: "<h1>Hello from Apache!</h1>"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
