#!/bin/bash
set -euo pipefail

#--- change to root ---
#sudo su # using this gives time out error for the Concert workflow SSH action
#RB-commented
#cd /root

# Update and install dependencies
#apt-get update -y
#apt-get install -y curl unzip jq

#RB- added
#sudo apt install unzip
###echo "running apt-get update"
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
ls
#sudo snap install aws-cli

#echo "running apt-get update"
#echo "aws install completed"
